### ISSUE TITLE
[Aeva-Media] Cache File outside of /gz

### ISSUE THREAD

**Issue by C3realGuy** [Wedge/wedge#32]
Every now and then an "Aeva-Sites.php" appears in /core/app/media. It looks like a cache file of all activated Sites for Aeva embed. Shouldn't this be placed in /gz/app(/media)? Because a clean of cache doesn't affect this file (of course).

**Comment by Nao** [comment]
It is a cache file yes. But it is also a different kind of file. Since no copy of its contents exists in the database, sadly, it can't be disposed of.
I think it doesn't cause much problems though...

**Comment by wintstar** [comment]
Is make Problems...
The database value you're trying to insert does not exist: id_file
Function: aeva_resetTransparency 
Warning (level 2): explode() expects parameter 2 to be string, array given
Apply Filter: Only show the errors from this file File: /xxx/webb/xx/xx/xxxxxx/htdocs/development/wedge/gz/app/Load.php
and many more.
It always overcrowded, the error log.
