### ISSUE TITLE
Production-ready?

### ISSUE THREAD

**Issue by Ariamiro** [Wedge/wedge#33]
Is Wedge production-ready?

**Comment by Nao** [comment]
Yes.
It has a few various bugs and missing features, but nobody seems to mind or notice them, so yeah it's production ready. Actually it had been for over a year.

**Comment by Nao** [comment]
*has

**Comment by Ariamiro** [comment]
Ok, thank you!

**Comment by Nao** [comment]
You're welcome.
If you find 'bugs that bother you', feel free to post an issue here of course.

**Comment by Ariamiro** [comment]
Ok, i installed Wedge on my server and i can't find bugs, it's awesome!

**Comment by Nao** [comment]
Told you so :)

2015-10-16 15:38 GMT+02:00 SávioSG <notifications@github.com>:

**Comment by chope1** [comment]
That's great!!!
