### ISSUE TITLE
[createPost] body type not regarding $settings['max_messageLength'] if zero

### ISSUE THREAD

**Issue by C3realGuy** [Wedge/wedge#36]
If $settings['max_messageLength'] is set to zero (unlimited length of posts), body type was set to 'string-65534'. This resulted in cropped posts if the consisted of more than 65534 characters.

Fix:
https://github.com/Wedge/wedge/pull/37/commits/63d1d8c3251a34ad62f1e9ab07d13233609dc526

**Comment by Nao** [comment]
I don't even know why this bit of code bothered to set a size for posts...

I mean, what do these 64kb even represent..? Some old MySQL limit?

**Comment by C3realGuy** [comment]
I don't know, maybe the default post length? Not sure about that.
