### ISSUE TITLE
Deprecated function name in class

### ISSUE THREAD

**Issue by halojoy** [Wedge/wedge#42]
I run PHP 7.
There is a deprecated function name. With the same name as the class.
This is not what one can do in PHP 7.

install/install.php Line number 1347:
Class ftp_connection
and
function ftp_connection()

I changed the name of function to 
function __construct()
and there was no longer any NOTICE.

**Comment by Nao** [comment]
Thanks!
Latest commit does that.


2017-01-08 19:05 GMT+01:00 Stefan <notifications@github.com>:
