### ISSUE TITLE
PHP 7 Warning in index.php

### ISSUE THREAD

**Issue by halojoy** [Wedge/wedge#51]
LINK:
..../wedge/index.php?action=viewremote;filename=latest-news.js

ISSUE:
Warning (level 2): call_user_func() expects parameter 1 to be a valid callback, function 'ViewRemote' not found or invalid function name

FILE, LINE NUMBER:
..../wedge/index.php
Line: 150

**Comment by Nao** [comment]
well, i get this kind of error from time to time. I'm not sure why it
happens. is it always from the same page?

It may be due to a file in gz/app/ being at 0 byte size, indicating a
failed cache process. (Wedge does check for those but I'm not sure why
sometimes it goes through...)

**Comment by C3realGuy** [comment]
For me it's always the ?action=viewremote;filename=latest-news.js page. Get them from time to time, looked into it sometimes, never got even close to the problem. Absolutely no idea. Doesn't break anything, just error.

http://wedge.org/pub/bugs/8658/viewremote-not-found-or-invalid-function-name/msg296661/#msg296661

**Comment by C3realGuy** [comment]
Made some progress on reproducing the error:

provoke.php
```
?php
error_reporting(E_ALL | E_STRICT);

$_SERVER['HTTP_HOST'] = '0.0.0.0';
$_SERVER['REQUEST_URI'] = '';

require('core/SSI.php');

// And important files.
loadSource(array(
	'Class-System',
	'QueryString',
	'Subs',
	'Errors',
	'Load',
	'Security',
));

// Register an error handler.
set_error_handler('error_handler');


$_REQUEST['filename'] = 'latest-news.js';

loadSource('ViewRemote');
call_user_func('ViewRemote');
```

provoke.sh
```
#!/bin/bash

while true; do
  php provoke.php &  PIDIOS=$!
  php provoke.php &  PIDMIX=$!
  wait $PIDIOS
  wait $PIDMIX
  rm ./gz/app/ViewRemote.php
done
```

You have to put both files into your wedge folder.
provoke.php imitates an request to ViewRemote. So basically loads ViewRemote.php
and tries to call_user_func('ViewRemote');. Other overhead is to pipe the errors right and stuff.

provoke.sh fires two executions of provoke.php at the same time. Besides that it kills gz/app/ViewRemote.php as soon as both exectutions are done. This will be repeated forever.
With this i'm able to reproduce 'Warning (level 2): call_user_func() expects parameter 1 to be a valid callback, function 'ViewRemote' not found or invalid function name ' quite easily.

Now the real fun part, see if some flock magic helps.

**Comment by Nao** [comment]
Oh, good!
Did you try with my latest commit, the one that logs the filesize or
something?

2017-02-06 19:13 GMT+01:00 C3realGuy <notifications@github.com>:

**Comment by C3realGuy** [comment]
I'm not using determine_action currenty, so your part won't get executed. But i will modify it and watch if something happens :D

**Comment by C3realGuy** [comment]
Let's discuss some more stuff on PR: https://github.com/Wedge/wedge/pull/53

**Comment by Nao** [comment]
(Fixed!)
