### ISSUE TITLE
Errorlog: A non-numeric value encountered 

### ISSUE THREAD

**Issue by C3realGuy** [Wedge/wedge#55]
Updated php to 7.1 and wedge to latest master. Will look into it, only happens if error log is empty. So to reproduce it you have to clear the errors.

```
Url: **/index.php?action=admin;area=logs;sa=errorlog 
Warning (level 2): A non-numeric value encountered 
Filter einschalten: Nur Fehler von dieser Datei anzeigen Datei: /*****/gz/app/Subs.php
Zeile: 2299
```

**Comment by Nao** [comment]
I'm guessing it should be fixed by adding (int) before $error_count on that
line. (Because it can also be initialized to an empty string, rather than
the number zero.)
I'll fix it locally, it'll be in my next batch of commits.


2017-02-21 15:52 GMT+01:00 C3realGuy <notifications@github.com>:

**Comment by Nao** [comment]
(I think I fixed this..?)
