### ISSUE TITLE
ManageSmileys: Undefined index: here 

### ISSUE THREAD

**Issue by C3realGuy** [Wedge/wedge#56]
Already popped up some times, leave it here as a reminder. Nothing looked broken, only an odd error. BTW, i like the smiley set at wedge.org, where did you get it? :D

```
index.php?action=admin;area=smileys;sa=modifyset;set=0 
Notice (level 8): Undefined index: here 
Zeile: 39
```

**Comment by Nao** [comment]
Thanks. Terrible one... Mostly SMF's fault :P
