### ISSUE TITLE
Who.english.php [no referral to the secure connection]

### ISSUE THREAD

**Issue by French77** [Wedge/wedge#62]
$txt['credits_wedge'] = '<a href="%2$s">Wedge</a> is copyright © %5$s by <a href="%3$s">%1$s</a>, all rights reserved. It is distributed under the <a href="%4$s">Wedge license</a>.';

When for example change the link into:
$txt['credits_wedge'] = '<a href="https://wedge.org/"target="_blank">Wedge</a> is copyright © %5$s by <a href="%3$s">%1$s</a>,all rights reserved. It is distributed under the <a href="%4$s">Wedge license</a>.';

Referral to the secure connection https://wedge.org/ is oké....also applies to the license and authors reference

**Comment by Nao** [comment]
I'm just not sure it's really useful. IIRC the http link is redirected to https anyway, and if I ever have to move between servers again, regenerating the certificate takes some time and is complicated, so it might mean the link might not work for longer...

(Okay, who am I kidding, no one's ever clicking that link anyway. :-P)
