### ISSUE TITLE
Email Templates Edit for other languages

### ISSUE THREAD

**Issue by dragomano** [Wedge/wedge#63]
ManageMail.template.php, line 75:
`emaillang=english`

It need to replaced with:
`emaillang=', $_REQUEST['emaillang'], '`

**Comment by Nao** [comment]
Thanks! I've never touched that page, wouldn't it be $lang['filename'] instead, like a few lines above..? (?)

**Comment by dragomano** [comment]
Wouldn't. A different array is there.

**Comment by Nao** [comment]
Okay I'm gonna commit because let's be crazy. :P It'll be in my next push.
If someone has a problem with this, feel free to talk!

**Comment by dragomano** [comment]
I have a new suggestion after a little testing.

1. Replace
`	foreach ($context['email_groups'] as $group_name => $group`
with
> $lang = isset($_REQUEST['emaillang'], $context['languages'][$_REQUEST['emaillang']]) ? $_REQUEST['emaillang'] : 'english';
	foreach ($context['email_groups'] as $group_name => $group

2. Replace
`				<dt><a href="<URL>?action=admin;area=mailqueue;sa=templates;emaillang=english;email=', $item, '">', $item, 
`
with
`				<dt><a href="<URL>?action=admin;area=mailqueue;sa=templates;emaillang=', $lang, ';email=', $item, '">', $item, `

**Comment by Nao** [comment]
I'm afraid I don't have time to look into this.
Can someone try & create a pull request for this problem..?

**Comment by Nao** [comment]
Closing for lack of interest from all parties involved.
