### ISSUE TITLE
Titles of threads in unviewable boards leaked by user profile

### ISSUE THREAD

**Issue by nsgomez** [Wedge/wedge#69]
## Steps to reproduce
1. Create a board invisible to guests but visible to members.
2. Sign in and create a thread in the board as a user.
3. Sign out and go to that user's profile.

## Behavior shown
The **Last post** field will reveal the title of the thread even if the user doesn't have the privileges to view it. They will not be able to view the thread itself, however.

**Comment by Nao** [comment]
Something to test...
core/app/Load.php
around line 1021
There should be a SQL statement with a 'WHERE' section. Replace it with:

			WHERE {query_see_board}
				AND m.id_member' . (count($new_loaded_ids) == 1 ? ' = {int:loaded_ids}' : ' IN ({array_int:loaded_ids})') . '
				AND {query_see_topic}

(Basically, adding "{query_see_board} AND" before the rest.)

This might/should fix your issue. I can't bother to look into {query_see_topic}, but I thought it took board permissions into account... (?)

**Comment by Nao** [comment]
Please confirm it fixes it...
