### ISSUE TITLE
Link insertion in index.template.php does not work

### ISSUE THREAD

**Issue by AlexL777** [Wedge/wedge#73]
Hi Developers,

with me the insertion of simple links in the index.template.php does not work. It then appears in the forum frontend of the error that something is "href".

After which format are simple links included in the index.template.php in the footer section? I would like to know that.

Thanks in advance.

P.S. does a URL have to be set to "echo ' "?

**Comment by Nao** [comment]
Sorry but you'll really need to look into PHP a bit more before you can start customizing your forum a lot. I can always do it for a price though. :P
