### ISSUE TITLE
Warning at install

### ISSUE THREAD

**Issue by halojoy** [Wedge/wedge#80]
Tried to download the wedge and install.

I get these warnings:
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\Apache24\htdocs\wedge\gz\app\Subs.php on line 1660

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\Apache24\htdocs\wedge\gz\app\Subs.php on line 1667

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\Apache24\htdocs\wedge\gz\app\Subs.php on line 1674

So I did not continue to install this script.

**Comment by Nao** [comment]
Thanks for the report!
